/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BiuA {
        "isActive"?: boolean;
        "label"?: string;
    }
    interface BiuButton {
        "label"?: string;
    }
    interface BiuCalendar {
        "dayHeaders"?: string[];
        "headerLabel"?: string;
        "label": string;
        "monthHeaders"?: string[];
    }
    interface BiuCheckbox {
        "checked"?: boolean;
        "label"?: string;
    }
    interface BiuDateBar {
        "days"?: number;
        "daysLabel"?: string[];
        "eventDates"?: string;
        "label"?: string;
        "monthsLabel"?: string[];
    }
    interface BiuDropdown {
        "icon"?: string;
        "label"?: string;
        "options"?: string | object | any;
    }
    interface BiuRoundedButton {
        "icon"?: string;
        "label"?: string;
    }
    interface BiuSearchBar {
        "defaultValue"?: string;
        "placeholder"?: string;
    }
    interface BiuSelect {
        "defaultValue"?: string | object | any;
        "options"?: string | object | any;
    }
}
declare global {
    interface HTMLBiuAElement extends Components.BiuA, HTMLStencilElement {
    }
    var HTMLBiuAElement: {
        prototype: HTMLBiuAElement;
        new (): HTMLBiuAElement;
    };
    interface HTMLBiuButtonElement extends Components.BiuButton, HTMLStencilElement {
    }
    var HTMLBiuButtonElement: {
        prototype: HTMLBiuButtonElement;
        new (): HTMLBiuButtonElement;
    };
    interface HTMLBiuCalendarElement extends Components.BiuCalendar, HTMLStencilElement {
    }
    var HTMLBiuCalendarElement: {
        prototype: HTMLBiuCalendarElement;
        new (): HTMLBiuCalendarElement;
    };
    interface HTMLBiuCheckboxElement extends Components.BiuCheckbox, HTMLStencilElement {
    }
    var HTMLBiuCheckboxElement: {
        prototype: HTMLBiuCheckboxElement;
        new (): HTMLBiuCheckboxElement;
    };
    interface HTMLBiuDateBarElement extends Components.BiuDateBar, HTMLStencilElement {
    }
    var HTMLBiuDateBarElement: {
        prototype: HTMLBiuDateBarElement;
        new (): HTMLBiuDateBarElement;
    };
    interface HTMLBiuDropdownElement extends Components.BiuDropdown, HTMLStencilElement {
    }
    var HTMLBiuDropdownElement: {
        prototype: HTMLBiuDropdownElement;
        new (): HTMLBiuDropdownElement;
    };
    interface HTMLBiuRoundedButtonElement extends Components.BiuRoundedButton, HTMLStencilElement {
    }
    var HTMLBiuRoundedButtonElement: {
        prototype: HTMLBiuRoundedButtonElement;
        new (): HTMLBiuRoundedButtonElement;
    };
    interface HTMLBiuSearchBarElement extends Components.BiuSearchBar, HTMLStencilElement {
    }
    var HTMLBiuSearchBarElement: {
        prototype: HTMLBiuSearchBarElement;
        new (): HTMLBiuSearchBarElement;
    };
    interface HTMLBiuSelectElement extends Components.BiuSelect, HTMLStencilElement {
    }
    var HTMLBiuSelectElement: {
        prototype: HTMLBiuSelectElement;
        new (): HTMLBiuSelectElement;
    };
    interface HTMLElementTagNameMap {
        "biu-a": HTMLBiuAElement;
        "biu-button": HTMLBiuButtonElement;
        "biu-calendar": HTMLBiuCalendarElement;
        "biu-checkbox": HTMLBiuCheckboxElement;
        "biu-date-bar": HTMLBiuDateBarElement;
        "biu-dropdown": HTMLBiuDropdownElement;
        "biu-rounded-button": HTMLBiuRoundedButtonElement;
        "biu-search-bar": HTMLBiuSearchBarElement;
        "biu-select": HTMLBiuSelectElement;
    }
}
declare namespace LocalJSX {
    interface BiuA {
        "isActive"?: boolean;
        "label"?: string;
        "onBiuOnClick"?: (event: CustomEvent<any>) => void;
    }
    interface BiuButton {
        "label"?: string;
        "onBiuOnClick"?: (event: CustomEvent<any>) => void;
    }
    interface BiuCalendar {
        "dayHeaders"?: string[];
        "headerLabel"?: string;
        "label"?: string;
        "monthHeaders"?: string[];
        "onBiuOnDateSelection"?: (event: CustomEvent<any>) => void;
    }
    interface BiuCheckbox {
        "checked"?: boolean;
        "label"?: string;
        "onBiuOnCheck"?: (event: CustomEvent<any>) => void;
    }
    interface BiuDateBar {
        "days"?: number;
        "daysLabel"?: string[];
        "eventDates"?: string;
        "label"?: string;
        "monthsLabel"?: string[];
        "onBiuOnClick"?: (event: CustomEvent<any>) => void;
    }
    interface BiuDropdown {
        "icon"?: string;
        "label"?: string;
        "onBiuOnOptionSelect"?: (event: CustomEvent<any>) => void;
        "options"?: string | object | any;
    }
    interface BiuRoundedButton {
        "icon"?: string;
        "label"?: string;
        "onBiuOnClick"?: (event: CustomEvent<any>) => void;
    }
    interface BiuSearchBar {
        "defaultValue"?: string;
        "onBiuOnChange"?: (event: CustomEvent<any>) => void;
        "onBiuOnReset"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
    }
    interface BiuSelect {
        "defaultValue"?: string | object | any;
        "onBiuOnOptionSelect"?: (event: CustomEvent<any>) => void;
        "options"?: string | object | any;
    }
    interface IntrinsicElements {
        "biu-a": BiuA;
        "biu-button": BiuButton;
        "biu-calendar": BiuCalendar;
        "biu-checkbox": BiuCheckbox;
        "biu-date-bar": BiuDateBar;
        "biu-dropdown": BiuDropdown;
        "biu-rounded-button": BiuRoundedButton;
        "biu-search-bar": BiuSearchBar;
        "biu-select": BiuSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "biu-a": LocalJSX.BiuA & JSXBase.HTMLAttributes<HTMLBiuAElement>;
            "biu-button": LocalJSX.BiuButton & JSXBase.HTMLAttributes<HTMLBiuButtonElement>;
            "biu-calendar": LocalJSX.BiuCalendar & JSXBase.HTMLAttributes<HTMLBiuCalendarElement>;
            "biu-checkbox": LocalJSX.BiuCheckbox & JSXBase.HTMLAttributes<HTMLBiuCheckboxElement>;
            "biu-date-bar": LocalJSX.BiuDateBar & JSXBase.HTMLAttributes<HTMLBiuDateBarElement>;
            "biu-dropdown": LocalJSX.BiuDropdown & JSXBase.HTMLAttributes<HTMLBiuDropdownElement>;
            "biu-rounded-button": LocalJSX.BiuRoundedButton & JSXBase.HTMLAttributes<HTMLBiuRoundedButtonElement>;
            "biu-search-bar": LocalJSX.BiuSearchBar & JSXBase.HTMLAttributes<HTMLBiuSearchBarElement>;
            "biu-select": LocalJSX.BiuSelect & JSXBase.HTMLAttributes<HTMLBiuSelectElement>;
        }
    }
}
