/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BiuCalendar {
        "dayHeaders": string[];
        "headerLabel": string;
        "label": string;
        "months": string[];
    }
}
declare global {
    interface HTMLBiuCalendarElement extends Components.BiuCalendar, HTMLStencilElement {
    }
    var HTMLBiuCalendarElement: {
        prototype: HTMLBiuCalendarElement;
        new (): HTMLBiuCalendarElement;
    };
    interface HTMLElementTagNameMap {
        "biu-calendar": HTMLBiuCalendarElement;
    }
}
declare namespace LocalJSX {
    interface BiuCalendar {
        "dayHeaders"?: string[];
        "headerLabel"?: string;
        "label"?: string;
        "months"?: string[];
        "onBiuOnDateSelection"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "biu-calendar": BiuCalendar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "biu-calendar": LocalJSX.BiuCalendar & JSXBase.HTMLAttributes<HTMLBiuCalendarElement>;
        }
    }
}
